//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pogym.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pogymEntities : DbContext
    {
        public pogymEntities()
            : base("name=pogymEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<attacks_types> attacks_types { get; set; }
        public virtual DbSet<pokemons> pokemons { get; set; }
        public virtual DbSet<pokemons_attacks> pokemons_attacks { get; set; }
        public virtual DbSet<pokemons_types> pokemons_types { get; set; }
        public virtual DbSet<types> types { get; set; }
        public virtual DbSet<types_types> types_types { get; set; }
        public virtual DbSet<attacks> attacks { get; set; }
        public virtual DbSet<attacks_charge> attacks_charge { get; set; }
        public virtual DbSet<attacks_quick> attacks_quick { get; set; }

        public System.Data.Entity.DbSet<pogym.Models.Pokemon> Pokemons { get; set; }
    }
}
