//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pogym.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pokemons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pokemons()
        {
            this.pokemons_attacks = new HashSet<pokemons_attacks>();
            this.pokemons1 = new HashSet<pokemons>();
            this.pokemons_types = new HashSet<pokemons_types>();
        }
    
        public int pokemon_id { get; set; }
        public Nullable<int> evolvefrom_pokemon_id { get; set; }
        public string name { get; set; }
        public string icon { get; set; }
        public string image { get; set; }
        public string url { get; set; }
        public decimal height_avg { get; set; }
        public decimal weight_avg { get; set; }
        public int combatpower_max { get; set; }
        public int attack_base { get; set; }
        public int defense_base { get; set; }
        public int stamina_base { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pokemons_attacks> pokemons_attacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pokemons> pokemons1 { get; set; }
        public virtual pokemons pokemons2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pokemons_types> pokemons_types { get; set; }
    }
}
