//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pogym.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pokemons_attacks
    {
        public int pokemon_attack_id { get; set; }
        public int pokemon_id { get; set; }
        public int attack_id { get; set; }
        public Nullable<decimal> true_damageps { get; set; }
    
        public virtual attacks attacks { get; set; }
        public virtual pokemons pokemons { get; set; }
    }
}
